import pytest

from ammasing_nlp.categories.med_discontinue import DISCONTINUE_PAT


@pytest.mark.parametrize('text', [
    'added to allergy list',
    'stopped',
    'discontinued',
    'continue the taper',
    'could not tolerate',
    'd fluoxetine',
    'd/c',
    'd/ced',
    'did not tolerate',
    'didn\'t like',
    'discontinue',
    'discontinued',
    'discontinuing',
    'trouble tolerating',
    'should stop',
    'hold off',
    'no longer take',
    'no sense in continuing',
    'not been taking',
    'prohibited him from taking it',
    'quit',
    'stop',
    'stopped',
    'stopping',
    'unable to continue',
    'very uncomfortable',
    'want to stop',
    'weaning',
    'went off',
    'will not take any further doses',
])
def test_discontinue_pat(text):
    assert(DISCONTINUE_PAT.search(text))


@pytest.mark.parametrize('text', [
    'stopped prozac',
    'citalopram was discontinued',
    'continue the taper from sertraline',
    'could not tolerate 20mg of prozac',
    'd fluoxetine',
    'd/c sertraline',
    'd/ced sertraline',
    'decrease citalopram',
    'desires to stop prozac',
    'did not tolerate celexa',
    'didn\'t like the side effects of the sertraline',
    'discontinuation of the medication',
    'discontinue bupropion',
    'discontinue their bupropion',
    'discontinued the fluoxetine',
    'discontinue usage of lexapro',
    'does not like the zoloft',
    'fluoxetine was discontinued',
    'trouble tolerating fluoxetine',
    'should stop the fluoxetine',
    'hold off amitriptyline',
    'no longer take zoloft',
    'no sense in continuing medication',
    'not been taking the meds',
    'not tolerating the medication',
    'off of citalopram',
    'prohibited her from taking it',
    'prozac stopped',
    'quit zoloft',
    'recommend stopping mirtazapine',
    'refuses to take any more of this rx',
    'stop mertazapine now',
    'stop taking anti-depressant',
    'stop the tramodol',
    'stopped citalopram',
    'stopped her citalopram',
    'stopped taking the citalopram',
    'stopping citalopram',
    'taper wellbutrin',
    'uncomfortable with zoloft',
    'want to stop remeron',
    'weaning the remeron',
    'went off fluoxetine',
])
def test_med_discontinue_pat(text):
    assert(DISCONTINUE_PAT.search(text))
